#! /bin/sh
#
# chkconfig: - 60 40
# description:	Compendium PadrinoAPI Workers
# processname: padrino
# pidfile: /var/run/padrino_workers.pid

. /etc/init.d/functions

export PATH=/root/.rbenv/shims:/root/.rbenv/bin:/root/.rbenv/shims:/root/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/root/bin

PROG="bundle exec sidekiq -C ./config/sidekiq.yml -r ./config/boot.rb"
PIDFILE="/var/run/padrino_workers/padrino_workers.pid"
LOCKFILE="/var/lock/subsys/padrino_workers"
MYNAME=$(basename $0)
USER="root"

if [ -f "/etc/sysconfig/${MYNAME}" ]; then
	. /etc/sysconfig/${MYNAME}
fi

start() {
	# Create dir if does not exist
	[ -d /var/run/padrino_workers ] || mkdir /var/run/padrino_workers

	cd /var/www/padrino_app
	daemon --make-pidfile ${PIDFILE} ${PROG} > /var/log/padrino_workers 2>&1
	RETVAL=$?

	echo
	[ $RETVAL -eq 0 ] && touch ${LOCKFILE}

}

stop() {
	if [ ! -f "$PIDFILE" ]; then
		return 0
	fi
	echo -n $"Stopping $PROG: "
	killproc -p ${PIDFILE}
	RETVAL=$?
	echo
	if [ $RETVAL -eq 0 ] ; then
		rm -f ${LOCKFILE} ${PIDFILE}
	fi

}

restart () {
	stop
	start
}


# See how we were called.
case "$1" in
	start)
	start
	;;
	stop)
	stop
	;;
	status)
	status -p $PIDFILE $prog
	RETVAL=$?
	;;
	restart)
	restart
	;;
	*)
	echo "Usage: $0 {start|stop|status|restart}"
	exit 1
esac

exit $RETVAL
