#! /bin/sh
#
# chkconfig: - 60 40
# description:	Compendium PadrinoAPI Workers
# processname: padrino
# pidfile: /var/run/padrino_workers.pid

. /etc/init.d/functions

# Check that networking is up.
. /etc/sysconfig/network

if [ "$NETWORKING" = "no" ]
then
	exit 1
fi


BUNDLE=/usr/bin/bundle

PROG="${BUNDLE} exec sidekiq -C ./config/sidekiq.yml -r ./config/boot.rb"
PIDFILE="/var/run/padrino_workers/padrino_workers.pid"
LOCKFILE="/var/lock/subsys/padrino_workers"
MYNAME=$(basename $0)
USER="root"

if [ -f "/etc/sysconfig/${MYNAME}" ]; then
	. /etc/sysconfig/${MYNAME}
fi

start() {
	# Create dir if does not exist
	[ -d /var/run/padrino_workers ] || mkdir /var/run/padrino_workers

	# Ensure that /var/run/padrino_workers has proper permissions
	if [ "`stat -c %U /var/run/padrino_workers`" != "$USER" ]; then
		chown $USER /var/run/padrino_workers
	fi

	cd /var/www/padrino_app
	daemon --user ${USER} --pidfile ${PIDFILE} ${PROG}  > /var/log/padrino_workers 2>&1
	RETVAL=$?

	echo
	[ $RETVAL -eq 0 ] && touch ${LOCKFILE}

}

stop() {
	if [ ! -f "$PIDFILE" ]; then
		return 0
	fi
	echo -n $"Stopping $prog: "
	killproc -p ${PIDFILE} ${BUNDLE}
	RETVAL=$?
	echo
	if [ $RETVAL -eq 0 ] ; then
		rm -f ${LOCKFILE} ${PIDFILE}
	fi

}

restart () {
	stop
	start
}


# See how we were called.
case "$1" in
	start)
	start
	;;
	stop)
	stop
	;;
	status)
	status -p $PIDFILE $prog
	RETVAL=$?
	;;
	restart)
	restart
	;;
	*)
	echo "Usage: $0 {start|stop|status|restart}"
	exit 1
esac

exit $RETVAL
